#!/bin/bash
cd frameworks/av
git apply -v ../../device/xiaomi/hermes/patches/framework_av/0001-libmedia-stub-out-MTK-specific-bits-audio-working.patch
git apply -v ../../device/xiaomi/hermes/patches/framework_av/0002-camera.patch
cd ../..
cd frameworks/base
git apply -v ../../device/xiaomi/hermes/patches/framework_base/0001-location-support-GNSS-extension-presumably-from-MTK.patch
git apply -v ../../device/xiaomi/hermes/patches/framework_base/0002-location-add-some-logs-just-to-be-confident.patch
git apply -v ../../device/xiaomi/hermes/patches/framework_base/0003-location-style-fix.patch
git apply -v ../../device/xiaomi/hermes/patches/framework_base/0004-NetworkMonitor-use-g.cn-for-connectivity-check.patch
git apply -v ../../device/xiaomi/hermes/patches/framework_base/0005-SystemUI-add-new-carrier-name-override-rule-for-Chin.patch
git apply -v ../../device/xiaomi/hermes/patches/framework_base/0006-add-com.mediatek-for-build.patch
git apply -v ../../device/xiaomi/hermes/patches/framework_base/0007-Update-for-mtk.patch
cd ../..
cd frameworks/opt/telephony
git apply -v ../../../system/device/xiaomi/hermes/patches/framework_opt_telephony/0001-Update-for-mtk.patch
cd ../../..
cd packages/services/Telephony
git apply -v ../../../device/xiaomi/hermes/patches/packages_services_Telpheony/0001-Update-for-mtk.patch
cd ~/android/system
source build/envsetup.sh
breakfast hermes
make -j2 bacon



